language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 4.0.0
before_script:
- npm start &
- npm install mocha-phantomjs -g
- phantomjs --version
script:
- npm test
- npm run browser-test
- npm run browser-test-cover
env:
  global:
  - secure: Ii32iXaX/LkgYtpDciuj4xE8OEKIdh6M58ttAOG4phFXqtzIjx4QWT2enw4l05M35AjVrLE6ZcyR46sje25CFVEDx+0JZ+icNh6/0TEN95xR+64rBAOWTugy1tc1cVwy3Pcol37pkVLzNvF97M1qyoL+zJX3yvrabzlG4B344QQ=
  - secure: gNNOyy0ZU/cKSpudRunolQhqYvyHG/1L+vMjobFkFq3aJOXJKZlxzErsd7BBi71hgOorADOqIKu5LPe5FRkHNASWld1OT5d6Kuv18wNDi8Govk1QU5Zt+Ib2wRlKHCtnk8XagnxTsQkIjikK6ZfsawR8fSbhCGj/ZS4TTIGbV7I=
